name = "streetcars-api"
main = "worker.js"
compatibility_date = "2026-06-10"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "chat-db"
database_id = "fab7f1ff-5398-4a89-a652-67238c6a41ea"
